Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Lint/Debugger:
  Enabled: false

Metrics/LineLength:
  Max: 88

Style/BlockComments:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Enabled: false
